In [4]:
import pandas as pd
df1=pd.read_csv(r"D:/BCA & MSC Core Notes/MSC/MSC 2ND YEAR/MSC Major project/Dataset/Berkeley.csv")
display(df1.head(5))
df2=pd.read_csv(r"D:/BCA & MSC Core Notes/MSC/MSC 2ND YEAR/MSC Major project/Dataset/CRU.csv")
display(df2.head(5))
df3=pd.read_csv(r"D:/BCA & MSC Core Notes/MSC/MSC 2ND YEAR/MSC Major project/Dataset/NASA.csv")
display(df3.head(5))
df4=pd.read_csv(r"D:/BCA & MSC Core Notes/MSC/MSC 2ND YEAR/MSC Major project/Dataset/NOAA.csv")
display(df4.head(5))

,Date,originally from https://storage.googleapis.com/berkeley-earth-temperature-hr/global/Global_TAVG_monthly.txt missing value -99 https://psl.noaa.gov/data/timeseries/month/
0,1850-01-01,-0.380
1,1850-02-01,-0.186
2,1850-03-01,-0.220
3,1850-04-01,-0.738
4,1850-05-01,-0.276

,Date,originally from from https://crudata.uea.ac.uk/cru/data/temperature/HadCRUT5.0Analysis_gl.txt missing value -9.999 https://psl.noaa.gov/data/timeseries/month/
0,1850-01-01,-0.734
1,1850-02-01,-0.360
2,1850-03-01,-0.627
3,1850-04-01,-0.605
4,1850-05-01,-0.532

,Date,originally from from https://data.giss.nasa.gov/gistemp/tabledata/GLB.Ts+dSST.txt missing value 9999 https://psl.noaa.gov/data/timeseries/month/
0,1880-01-01,-0.19
1,1880-02-01,-0.25
2,1880-03-01,-0.09
3,1880-04-01,-0.17
4,1880-05-01,-0.10

,Date,originally from https://www.ncei.noaa.gov/data/noaa-global-surface-temperature/v6/access/timeseries/ missing value -99 https://psl.noaa.gov/data/timeseries/month/
0,1850-01-01,-1.046
1,1850-02-01,-0.777
2,1850-03-01,-0.853
3,1850-04-01,-0.990
4,1850-05-01,-0.839

In [5]:
import numpy as np

# Standardize column names and convert 'Date' to datetime objects for each DataFrame

df1.columns = ['Date', 'Berkeley_Temperature']
df1['Date'] = pd.to_datetime(df1['Date'])
df1['Berkeley_Temperature'] = pd.to_numeric(df1['Berkeley_Temperature'], errors='coerce')

df2.columns = ['Date', 'CRU_Temperature']
df2['Date'] = pd.to_datetime(df2['Date'])
df2['CRU_Temperature'] = pd.to_numeric(df2['CRU_Temperature'], errors='coerce')

df3.columns = ['Date', 'NASA_Temperature']
df3['Date'] = pd.to_datetime(df3['Date'])
df3['NASA_Temperature'] = pd.to_numeric(df3['NASA_Temperature'], errors='coerce')

df4.columns = ['Date', 'NOAA_Temperature']
df4['Date'] = pd.to_datetime(df4['Date'])
df4['NOAA_Temperature'] = pd.to_numeric(df4['NOAA_Temperature'], errors='coerce')

# Merge the dataframes on the 'Date' column
combined_df = pd.merge(df1, df2, on='Date', how='outer')
combined_df = pd.merge(combined_df, df3, on='Date', how='outer')
combined_df = pd.merge(combined_df, df4, on='Date', how='outer')

combined_df.to_csv(r"D:\BCA & MSC Core Notes\MSC\MSC 2ND YEAR\MSC Major project\Dataset\combined_df.csv")